package:
  name: statsmodels
  version: {{ GIT_BUILD_STR }}

source:
  git_url: https://github.com/statsmodels/statsmodels.git

build:
  number: {{ GIT_DESCRIBE_NUMBER|int if GIT_DESCRIBE_NUMBER else 0}}

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - pandas
    - patsy

  run:
    - python
    - numpy
    - cython
    - numpy
    - scipy
    - pandas
    - patsy

test:
  imports:
    - statsmodels

about:
  home: http://statsmodels.sourceforge.net/
  license : BSD License
