package:
  name: statsmodels
  version: 0.8.0

source:
  git_url: https://github.com/statsmodels/statsmodels.git

build:
  number: {{ 0 }}

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - pandas
    - patsy

  run:
    - python
    - numpy
    - cython
    - numpy
    - scipy
    - pandas
    - patsy

test:
  imports:
    - statsmodels

about:
  home: http://statsmodels.sourceforge.net/
  license : BSD License
